name: e_commerce
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

#------------------- PACKAGES-------------------#
dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6

#Product Specific
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #------------------- ASSETS-------------------#
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/logs/

  #------------------- FONTS-------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
